# -*- coding: utf-8 -*-
# vim: ft=yaml
---
include:
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Rules.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Runners/apps.education-docker.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Lint/Commitlint.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Release/Semantic-release.yaml

stages:
  - initial-checks
  - release

variables:
  STABLE_BRANCH: master

###############################################################################
# `initial-checks` stage: `commitlint`
###############################################################################
# Override default `commitlint` stage
commitlint:
  stage: initial-checks


###############################################################################
# `release` stage: `semantic-release`
###############################################################################
# the `semantic-release` job is defined in `templates/Release/Semantic-Release.yaml`
