# -*- coding: utf-8 -*-
# vim: ft=yaml
---
include:
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Rules.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Runners/apps.education-docker.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Lint/Commitlint.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Docker.yaml
  - project: EOLE/infra/ci-tools
    ref: stable
    file: /templates/Release/Semantic-release.yaml

stages:
  - initial-checks
  - build
  - release

variables:
  STABLE_BRANCH: master
  IMAGE_NAME: lookup-server

###############################################################################
# `initial-checks` stage: `commitlint`
###############################################################################
# Override default `commitlint` stage
commitlint:
  stage: initial-checks


###############################################################################
# `build` stage: `build-docker`
###############################################################################
# The name of the built image is define globally by `$IMAGE_NAME`
build-docker:
  extends: .build-docker-image


###############################################################################
# `release` stage: `semantic-release`
###############################################################################
# the `semantic-release` job is defined in `templates/Release/Semantic-Release.yaml`
